import { createRequire } from 'node:module';
import { defineConfig, type DefaultTheme } from 'vitepress';

const require = createRequire(import.meta.url);

// The sidebar is generated by typedoc (`npm run predocs`). Import it safely so
// that `vitepress` does not crash before typedoc has run for the first time.
let typedocSidebar: DefaultTheme.SidebarItem[] = [];
try {
  typedocSidebar = require('../api/typedoc-sidebar.json');
} catch {
  // typedoc has not generated the sidebar yet; fall back to an empty sidebar.
  typedocSidebar = [];
}

// https://vitepress.dev/reference/site-config
export default defineConfig({
  srcDir: '.',
  base: '/rtsp/',
  title: '@seydx/rtsp',
  description: 'RTSP media relay that fans out a single upstream source to many consumers (RTSP server, FFmpeg, raw callbacks) with two-way audio support',
  lastUpdated: true,
  themeConfig: {
    nav: [
      { text: 'Guide', link: '/' },
      { text: 'API Reference', link: '/api/' },
    ],
    sidebar: typedocSidebar,
    search: {
      provider: 'local',
    },

    socialLinks: [{ icon: 'github', link: 'https://github.com/seydx/rtsp' }],
  },
});
